/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/AWTForms/Frame.java to edit this template
 */
package p5pcd;

import java.awt.Color;
import static java.lang.Thread.sleep;
import java.util.Random;

/**
 *
 * @author alepd
 */
public class Frame extends java.awt.Frame {

    /**
     * Creates new form Frame
     */
    public Frame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Exit the Application
     */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        Frame frame = new Frame();
        frame.setSize(1200, 600);
        frame.setBackground(Color.black);
        frame.setLocation(150, 100);
        frame.setVisible(true);
        
        CanvasCentro canvas = new CanvasCentro(1200, 600);
        Centro centro = new Centro(canvas);
        frame.add(canvas);

        for (int i = 1; i <= 10; i++) {
            Runnable cliente;
            if (Math.random() <= 0.4) {
                cliente = new Rehab(centro);
            } else {
                cliente = new Masaje(centro);
            }

            Thread hiloCliente = new Thread(cliente);
            hiloCliente.start();

            Random rand = new Random(System.currentTimeMillis());
            int tiempoSleep = (1 + rand.nextInt(2)) * 1000;
            try {
                sleep(tiempoSleep);
            } catch (InterruptedException e) {
                System.out.println("interrupted exception");
            }
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
